bot:
  name: "My AI bot!"
  token: "my_bot_token_keep_secret"
  hfToken: "token_from_hf"
  ownerId: "580050773522513920"
maxEntriesPerOwner: 1
hostConstraints:
  maxSimultaneousMakeRequests: 1
  totalImagesInMakeCommand: 4
timeouts:
  discoDiffusion:
    imageNotAppearing: 10
    imageNotUpdating: 10
  stableDiffusion:
    imageNotAppearing: 30
    imageNotUpdating: 30
grpcServer:
  host: "xxxx.wolf.jina.ai"
  port: 443
  plainText: false
imagesFolder: "/app"
shareChannelID: "1015964690800726158"