bot:
  name: "Thingy"
  token: "my_bot_token_keep_secret"
  hfToken: "token_from_hf"
  ownerId: "my_discord_id"
hostConstraints:
  maxEntriesPerOwner: 1
  totalImagesInMakeCommand: 4
databasePath: "./db.sqlite"
imagesFolder: "./images"
shareChannelID: "my_share_channel_id"
redisHost: redis://redis:6379