#!/bin/bash
arguments="--project-name=thingy --port=8000 --flow-yml-path=/opt/thingy/flow_server.yml"
if [[ ! -z "$ALTERNATE_URL" ]]; then
    echo "Setting alternate URL to JCloudKeeper"
    arguments="$arguments --alternate-url=$ALTERNATE_URL"
fi
echo "Running JCloud with arguments: $arguments"
keep_my_jcloud $(echo $arguments) &
echo "Running thingy jar"
java -jar Thingy.jar data/config.yml
